services:
  mongodb:
    image: mongo:7.0
    container_name: github-webhook-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: github_webhook_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - webhook-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: github-webhook-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/github_webhook_db?authSource=admin
      - GITHUB_WEBHOOK_SECRET=
      - FLASK_ENV=production
    depends_on:
      - mongodb
    networks:
      - webhook-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: github-webhook-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - webhook-network

volumes:
  mongodb_data:

networks:
  webhook-network:
    driver: bridge
